// Content keys used across the site - defines what can be edited
export const CONTENT_KEYS = [
  // Background Images (URL or path like /images/hero.png)
  { key: "bg.hero.home", label: "Home Hero Background", page: "home", section: "Backgrounds" },
  { key: "bg.hero.keynote", label: "Keynote Hero Background", page: "keynote", section: "Backgrounds" },
  { key: "bg.achievements", label: "Achievements Section Background", page: "home", section: "Backgrounds" },
  { key: "bg.video.thumbnail", label: "Video Modal Thumbnail (Speaker page)", page: "keynote", section: "Backgrounds" },
  // Program cards (Work With Brian section)
  { key: "program1.image", label: "Program 1 - Inner Circle Card Image", page: "home", section: "Backgrounds" },
  { key: "program2.image", label: "Program 2 - 1-on-1 Coaching Card Image", page: "home", section: "Backgrounds" },
  { key: "program3.image", label: "Program 3 - Keynotes Card Image", page: "home", section: "Backgrounds" },
  // Home page - section images
  { key: "img.freeTraining", label: "Free Training Section Image", page: "home", section: "Backgrounds" },
  { key: "img.quote", label: "Quote Section Background", page: "home", section: "Backgrounds" },
  { key: "img.workLessEarnMore", label: "Work Less Earn More Section Image", page: "home", section: "Backgrounds" },
  { key: "img.typicalOutcomes.bg", label: "Typical Outcomes Section Background", page: "home", section: "Backgrounds" },
  { key: "img.typicalOutcomes.brian", label: "Typical Outcomes - Brian Photo", page: "home", section: "Backgrounds" },
  { key: "img.typicalOutcomes.tony", label: "Typical Outcomes - Tony Robbins Photo", page: "home", section: "Backgrounds" },
  { key: "img.brianStory", label: "Brian Story Section Image", page: "home", section: "Backgrounds" },
  { key: "img.attractDontChase.plus", label: "Attract Don't Chase - Plus Icon", page: "home", section: "Backgrounds" },
  { key: "img.attractDontChase.people", label: "Attract Don't Chase - People Icon", page: "home", section: "Backgrounds" },
  { key: "img.navbar.home", label: "Navbar Logo (Home)", page: "home", section: "Backgrounds" },
  { key: "img.footer.home", label: "Footer Logo (Home)", page: "home", section: "Backgrounds" },
  // Keynote page - section images
  { key: "img.navbar.keynote", label: "Navbar Logo (Keynote)", page: "keynote", section: "Backgrounds" },
  { key: "img.footer.keynote", label: "Footer Logo (Keynote)", page: "keynote", section: "Backgrounds" },
  { key: "img.keynote.eventPlanners", label: "Event Planners Section Image", page: "keynote", section: "Backgrounds" },
  { key: "img.keynote.transformation", label: "Transformation Section Image", page: "keynote", section: "Backgrounds" },
  { key: "img.keynote.book", label: "Book Section Image", page: "keynote", section: "Backgrounds" },
  // Attract Business page
  { key: "img.attract.hero", label: "Attract Business Hero Image", page: "attract-business", section: "Backgrounds" },
  // Home page
  { key: "hero.headline", label: "Hero Headline", page: "home", section: "Hero" },
  { key: "hero.subheadline", label: "Hero Subheadline", page: "home", section: "Hero" },
  { key: "hero.paragraph1", label: "Hero Paragraph 1", page: "home", section: "Hero" },
  { key: "hero.paragraph2", label: "Hero Paragraph 2", page: "home", section: "Hero" },
  { key: "hero.paragraph3", label: "Hero Paragraph 3", page: "home", section: "Hero" },
  { key: "hero.tagline", label: "Hero Tagline (blue text)", page: "home", section: "Hero" },
  { key: "hero.ctaText", label: "Hero CTA Button Text", page: "home", section: "Hero" },
  { key: "hero.ctaUrl", label: "Hero CTA Button URL", page: "home", section: "Hero" },
  { key: "achievements.heading", label: "Achievements Section Heading", page: "home", section: "Achievements" },
  { key: "achievements.subheading", label: "Achievements Subheading", page: "home", section: "Achievements" },
  { key: "achievements.item1", label: "Achievement 1", page: "home", section: "Achievements" },
  { key: "achievements.item2", label: "Achievement 2", page: "home", section: "Achievements" },
  { key: "achievements.item3", label: "Achievement 3", page: "home", section: "Achievements" },
  // Keynote page
  { key: "keynote.hero.headline", label: "Keynote Hero Quote", page: "keynote", section: "Hero" },
  { key: "keynote.hero.ctaText1", label: "Keynote CTA 1 (Video Clips)", page: "keynote", section: "Hero" },
  { key: "keynote.hero.ctaText2", label: "Keynote CTA 2 (Book Brian)", page: "keynote", section: "Hero" },
  { key: "keynote.hero.ctaUrl2", label: "Keynote CTA 2 URL", page: "keynote", section: "Hero" },
  // Work With Brian section
  { key: "work.heading", label: "Work With Brian - Section Heading", page: "home", section: "Work With Brian" },
  { key: "work.program1.title", label: "Program 1 - Title", page: "home", section: "Work With Brian" },
  { key: "work.program1.desc", label: "Program 1 - Description", page: "home", section: "Work With Brian" },
  { key: "work.program1.buttonText", label: "Program 1 - Button Text", page: "home", section: "Work With Brian" },
  { key: "work.program1.url", label: "Program 1 - Button URL", page: "home", section: "Work With Brian" },
  { key: "work.program2.title", label: "Program 2 - Title", page: "home", section: "Work With Brian" },
  { key: "work.program2.desc", label: "Program 2 - Description", page: "home", section: "Work With Brian" },
  { key: "work.program2.buttonText", label: "Program 2 - Button Text", page: "home", section: "Work With Brian" },
  { key: "work.program2.url", label: "Program 2 - Button URL", page: "home", section: "Work With Brian" },
  { key: "work.program3.title", label: "Program 3 - Title", page: "home", section: "Work With Brian" },
  { key: "work.program3.desc", label: "Program 3 - Description", page: "home", section: "Work With Brian" },
  { key: "work.program3.buttonText", label: "Program 3 - Button Text", page: "home", section: "Work With Brian" },
  { key: "work.program3.url", label: "Program 3 - Button URL", page: "home", section: "Work With Brian" },
  // Attract Don't Chase section
  { key: "attract.heading", label: "Attract Section - Main Heading", page: "home", section: "Attract Don't Chase" },
  { key: "attract.subheading", label: "Attract Section - Subheading", page: "home", section: "Attract Don't Chase" },
  { key: "attract.intro1", label: "Attract Section - Intro Paragraph 1", page: "home", section: "Attract Don't Chase" },
  { key: "attract.intro2", label: "Attract Section - Intro Paragraph 2", page: "home", section: "Attract Don't Chase" },
  { key: "attract.proofLabel", label: "Attract Section - Proof Label", page: "home", section: "Attract Don't Chase" },
  { key: "attract.spendLess.title", label: "Spend Less Box - Title", page: "home", section: "Attract Don't Chase" },
  { key: "attract.spendLess.p1", label: "Spend Less Box - Paragraph 1", page: "home", section: "Attract Don't Chase" },
  { key: "attract.spendLess.p2", label: "Spend Less Box - Paragraph 2", page: "home", section: "Attract Don't Chase" },
  { key: "attract.readyToAct.title", label: "Ready to Act Box - Title", page: "home", section: "Attract Don't Chase" },
  { key: "attract.readyToAct.p1", label: "Ready to Act Box - Paragraph 1", page: "home", section: "Attract Don't Chase" },
  { key: "attract.readyToAct.p2", label: "Ready to Act Box - Paragraph 2", page: "home", section: "Attract Don't Chase" },
  { key: "attract.readyToAct.p3", label: "Ready to Act Box - Paragraph 3", page: "home", section: "Attract Don't Chase" },
  { key: "attract.cta1", label: "Attract CTA - Line 1", page: "home", section: "Attract Don't Chase" },
  { key: "attract.cta2", label: "Attract CTA - Line 2", page: "home", section: "Attract Don't Chase" },
  { key: "attract.card1.desc", label: "Attract Card 1 - Description", page: "home", section: "Attract Don't Chase" },
  { key: "attract.card1.buttonText", label: "Attract Card 1 - Button Text", page: "home", section: "Attract Don't Chase" },
  { key: "attract.card1.url", label: "Attract Card 1 - Button URL", page: "home", section: "Attract Don't Chase" },
  { key: "attract.card2.desc", label: "Attract Card 2 - Description", page: "home", section: "Attract Don't Chase" },
  { key: "attract.card2.buttonText", label: "Attract Card 2 - Button Text", page: "home", section: "Attract Don't Chase" },
  { key: "attract.card2.url", label: "Attract Card 2 - Button URL", page: "home", section: "Attract Don't Chase" },
  // Typical Outcomes section
  { key: "outcomes.heading1", label: "Outcomes - Heading Line 1", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.heading2", label: "Outcomes - Heading Line 2", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.heading3", label: "Outcomes - Heading Line 3", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.statement", label: "Outcomes - Opening Statement", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.section1.title", label: "Outcomes Section 1 - Title", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.section1.p1", label: "Outcomes Section 1 - Paragraph 1", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.section1.p2", label: "Outcomes Section 1 - Paragraph 2", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.section2.title", label: "Outcomes Section 2 - Title", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.section2.p1", label: "Outcomes Section 2 - Paragraph 1", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.section2.p2", label: "Outcomes Section 2 - Paragraph 2", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.section3.title", label: "Outcomes Section 3 - Title", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.section3.p", label: "Outcomes Section 3 - Paragraph", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.section4.title", label: "Outcomes Section 4 - Title", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.section4.p", label: "Outcomes Section 4 - Paragraph", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.closing", label: "Outcomes - Closing Statement", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.outcome1.title", label: "Outcome 1 - Title", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.outcome1.desc", label: "Outcome 1 - Description", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.outcome2.title", label: "Outcome 2 - Title", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.outcome2.desc", label: "Outcome 2 - Description", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.outcome3.title", label: "Outcome 3 - Title", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.outcome3.desc", label: "Outcome 3 - Description", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.outcome4.title", label: "Outcome 4 - Title", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.outcome4.desc", label: "Outcome 4 - Description", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.outcome5.title", label: "Outcome 5 - Title", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.outcome5.desc", label: "Outcome 5 - Description", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.cta1.desc", label: "Outcomes CTA 1 - Description", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.cta1.buttonText", label: "Outcomes CTA 1 - Button Text", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.cta1.url", label: "Outcomes CTA 1 - Button URL", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.cta2.desc", label: "Outcomes CTA 2 - Description", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.cta2.buttonText", label: "Outcomes CTA 2 - Button Text", page: "home", section: "Typical Outcomes" },
  { key: "outcomes.cta2.url", label: "Outcomes CTA 2 - Button URL", page: "home", section: "Typical Outcomes" },
  // Brian Story section
  { key: "story.headline", label: "Brian Story - Main Headline", page: "home", section: "Brian Story" },
  { key: "story.subheadline", label: "Brian Story - Subheadline", page: "home", section: "Brian Story" },
  { key: "story.p1", label: "Brian Story - Paragraph 1", page: "home", section: "Brian Story" },
  { key: "story.p2", label: "Brian Story - Paragraph 2", page: "home", section: "Brian Story" },
  { key: "story.p3", label: "Brian Story - Paragraph 3", page: "home", section: "Brian Story" },
  { key: "story.p4", label: "Brian Story - Paragraph 4", page: "home", section: "Brian Story" },
  { key: "story.quote", label: "Brian Story - Quote", page: "home", section: "Brian Story" },
  { key: "story.intro", label: "Brian Story - Principles Intro", page: "home", section: "Brian Story" },
  { key: "story.principlesHeading", label: "Brian Story - Principles Heading", page: "home", section: "Brian Story" },
  { key: "story.principle1.title", label: "Principle 1 - Title", page: "home", section: "Brian Story" },
  { key: "story.principle1.desc", label: "Principle 1 - Description", page: "home", section: "Brian Story" },
  { key: "story.principle2.title", label: "Principle 2 - Title", page: "home", section: "Brian Story" },
  { key: "story.principle2.desc", label: "Principle 2 - Description", page: "home", section: "Brian Story" },
  { key: "story.principle3.title", label: "Principle 3 - Title", page: "home", section: "Brian Story" },
  { key: "story.principle3.desc", label: "Principle 3 - Description", page: "home", section: "Brian Story" },
  // Quote section
  { key: "quote.text", label: "Quote Section - Quote Text", page: "home", section: "Quote" },
  { key: "quote.attribution", label: "Quote Section - Attribution", page: "home", section: "Quote" },
  { key: "quote.desc", label: "Quote Section - Description", page: "home", section: "Quote" },
  { key: "quote.buttonText", label: "Quote Section - Button Text", page: "home", section: "Quote" },
  { key: "quote.buttonUrl", label: "Quote Section - Button URL", page: "home", section: "Quote" },
  // What You Will Learn section
  { key: "learn.label", label: "Learn Section - Label", page: "home", section: "What You Will Learn" },
  { key: "learn.heading", label: "Learn Section - Heading", page: "home", section: "What You Will Learn" },
  { key: "learn.intro", label: "Learn Section - Intro Paragraph", page: "home", section: "What You Will Learn" },
  { key: "learn.buttonText", label: "Learn Section - Button Text", page: "home", section: "What You Will Learn" },
  { key: "learn.buttonUrl", label: "Learn Section - Button URL", page: "home", section: "What You Will Learn" },
  { key: "learn.item1.title", label: "Learn Item 1 - Title", page: "home", section: "What You Will Learn" },
  { key: "learn.item1.desc", label: "Learn Item 1 - Description", page: "home", section: "What You Will Learn" },
  { key: "learn.item2.title", label: "Learn Item 2 - Title", page: "home", section: "What You Will Learn" },
  { key: "learn.item2.desc", label: "Learn Item 2 - Description", page: "home", section: "What You Will Learn" },
  { key: "learn.item3.title", label: "Learn Item 3 - Title", page: "home", section: "What You Will Learn" },
  { key: "learn.item3.desc", label: "Learn Item 3 - Description", page: "home", section: "What You Will Learn" },
  { key: "learn.item4.title", label: "Learn Item 4 - Title", page: "home", section: "What You Will Learn" },
  { key: "learn.item4.desc", label: "Learn Item 4 - Description", page: "home", section: "What You Will Learn" },
  // Work Less Earn More section
  { key: "workless.headline", label: "Work Less Section - Headline", page: "home", section: "Work Less Earn More" },
  { key: "workless.desc", label: "Work Less Section - Description", page: "home", section: "Work Less Earn More" },
  { key: "workless.buttonText", label: "Work Less Section - Button Text", page: "home", section: "Work Less Earn More" },
  { key: "workless.buttonUrl", label: "Work Less Section - Button URL", page: "home", section: "Work Less Earn More" },
  // Meta / site-wide
  { key: "meta.title", label: "Site Title", page: "all", section: "Meta" },
  { key: "meta.description", label: "Site Description", page: "all", section: "Meta" },
  // Social & Contact
  { key: "social.facebook", label: "Facebook URL", page: "all", section: "Social" },
  { key: "social.instagram", label: "Instagram URL", page: "all", section: "Social" },
  { key: "social.linkedin", label: "LinkedIn URL", page: "all", section: "Social" },
  { key: "social.youtube", label: "YouTube URL", page: "all", section: "Social" },
  { key: "contact.email", label: "Contact Email", page: "all", section: "Social" },
  { key: "contact.phone", label: "Contact Phone", page: "all", section: "Social" },
] as const;
