export const DEFAULT_CONTENT: Record<string, string> = {
  "bg.hero.home": "/images/Frame 8.png",
  "bg.hero.keynote": "/hero_section1.png",
  "bg.achievements": "",
  "bg.video.thumbnail": "/hero_section1.png",
  "program1.image": "/three_images/Ekran Resmi 2026-02-10 15.20.04 1.png",
  "program2.image": "/three_images/Ekran Resmi 2026-02-10 15.20.24 1.png",
  "program3.image": "/images/HS Biz Planning 014 1.png",
  "img.freeTraining": "/images/free training.png",
  "img.quote": "/hero_section1.png",
  "img.workLessEarnMore": "/images/image (32) 1.png",
  "img.typicalOutcomes.bg": "/background.png",
  "img.typicalOutcomes.brian": "/images/brian18.png",
  "img.typicalOutcomes.tony": "/Tony_Robbins_court.png",
  "img.brianStory": "/images/Frame 1000007768.png",
  "img.attractDontChase.plus": "/images/plus_icon.png",
  "img.attractDontChase.people": "/images/people_icon.png",
  "img.navbar.home": "/images/main logo-coaching-white.png",
  "img.footer.home": "/images/brian_moses_footer_logo.png",
  "img.navbar.keynote": "/images/speakerpage_logo/main logo-speaker-white.png",
  "img.footer.keynote": "/images/speakerpage_logo/main logo-speaker-dark.png",
  "img.keynote.eventPlanners": "/three_images/Ekran Resmi 2026-02-10 15.21.03 1.png",
  "img.keynote.transformation": "/images/Frame 1000007768.png",
  "img.keynote.book": "/images/Frame 8.png",
  "img.attract.hero": "/Brian_Moses.png",
  "hero.headline": "Attract, Don't Chase.",
  "hero.subheadline": "More of What Your Doing Won't Fix Your Business - Systems Will.",
  "hero.paragraph1": "A Proven System that helps you close more deals - without chasing leads, spending tons of money for leads, or burning out.",
  "hero.paragraph2": "Brian Moses opens his entire playbook - built from selling over 3,500 homes - and walks you step-by-step through exactly what to do.",
  "hero.paragraph3": "Follow the system, and the results take care of themselves.",
  "hero.tagline": "For Agents who want consistency and predictability in their business --- Clear. Practical. No hype.",
  "hero.ctaText": "See the System",
  "hero.ctaUrl": "https://inner-circle.brianmoses.com/how-to-get-3-new-listings-fast-page",
  "achievements.heading": "Here's Why Agents Trust Brian's System",
  "achievements.subheading": "Brian Has Inspired More Than 50,000 Real Estate Agents & Industry Professionals Across North America Including All Major Brands",
  "achievements.item1": "Named one of the 125 Most Influential People in Real Estate (Success Magazine)",
  "achievements.item2": "Ranked #2 Worldwide in a major real estate franchise, 7 years in the Top 10",
  "achievements.item3": "Brian Moses coaches and trains North America's most successful agents. These agents average over $1 Million Dollars in Annual Income and you can too.",
  "social.facebook": "https://www.facebook.com/BrianRichardMoses",
  "social.instagram": "https://www.instagram.com/coachbrianmoses/",
  "social.linkedin": "https://www.linkedin.com/in/brianmoses/",
  "social.youtube": "https://www.youtube.com/@BMosesNH",
  "contact.email": "Brian@BrianMoses.com",
  "contact.phone": "+16038601104",
  "meta.title": "Brian Moses | #2 Worldwide Real Estate Coach & Keynote Speaker | Attract, Don't Chase",
  "meta.description": "Discover the proven Attract, Don't Chase system from Brian Moses — a #2 worldwide ranked real estate agent, top real estate coach, and in‑demand keynote speaker.",
  "work.heading": "Let Brian Show You How to Stand Out in Your Market, Close More Deals and Enjoy a Balanced Life.",
  "work.program1.title": "Inner Circle Group Coaching",
  "work.program1.desc": "Accelerate Your Results! For the agent producing 0-15 sales annually, income is under $200,000 and they want a system and process that's predictable, reliable and duplicatable to produce more FAST!",
  "work.program1.buttonText": "Inner Circle Group Coaching",
  "work.program1.url": "https://inner-circle.brianmoses.com/how-to-get-3-new-listings-fast-page",
  "work.program2.title": "1 on 1 Personalized & Customized Coaching",
  "work.program2.desc": "For the Producer and/or Team Leader doing $200,000+ a year, wants more but without giving up their life. This is a 1 on 1 experience that will transform your business and life at scale. Apply for your free business evaluation call and secure your spot today.",
  "work.program2.buttonText": "Apply Now",
  "work.program2.url": "https://calendly.com/coachbrianmoses/30-minute-business-assessment-clone",
  "work.program3.title": "In Person Keynotes and Live Training",
  "work.program3.desc": "Motivational. Inspiring. Unforgettable. And Always Authentic. For Companies, Brokerages, or Conferences that turn moments into momentum",
  "work.program3.buttonText": "Learn More",
  "work.program3.url": "https://calendly.com/coachbrianmoses/discuss-booking-brian-for-your-event-clone",
  "attract.heading": "Why The Opposite of What You've Been Taught\nWorks 1,000x Better!",
  "attract.subheading": "Invert the Pyramid... or You'll Spend The Rest of Your Life Chasing What Should Be Chasing You.",
  "attract.intro1": "You've been told the path to success is cold calls, door knocking, and relentless hustle. But what if the real power move is doing less of what burns you out, and more of what brings results?",
  "attract.intro2": "",
  "attract.proofLabel": "Here's the proof:",
  "attract.spendLess.title": "Spend Less, Earn More",
  "attract.spendLess.p1": "We help you dramatically cut costs - starting with your cost per lead and cost per sale. By leveraging proven best practices, low cost and free lead sources available to you and smarter strategies, you get a higher ROI without relying on expensive 3rd party platforms or having to pay hefty referral fees.",
  "attract.spendLess.p2": "Instead of building these 3rd party's brands, you'll optimize everything you're already doing and strengthen your own brand, positioning yourself as a dominant player in your market.",
  "attract.readyToAct.title": "Work With People Who Are Ready to Act",
  "attract.readyToAct.p1": "Understand there is a huge difference between people and people who are actually thinking of buying or selling... Most Realtors are trained to prospect people. That is massively time consuming!",
  "attract.readyToAct.p2": "Imagine being able to only have to talk to people who are already thinking about buying or selling...",
  "attract.readyToAct.p3": "Exhausting follow up goes way down, conversion goes way up! When you are talking to the right people (buyers and sellers) you can talk to far fewer and sell a ton more homes!",
  "attract.cta1": "This isn't difficult, it's time to Stop thinking like a Realtor and create a business that is consistent, predictable and serves your life.",
  "attract.cta2": "Ready to Make the Transformation?",
  "attract.card1.desc": "For the agent producing 0-15 sales annually, income is under $200,000 and they want a system and process that's predictable, reliable and duplicatable to produce more FAST!",
  "attract.card1.buttonText": "Inner Circle Group Coaching",
  "attract.card1.url": "https://inner-circle.brianmoses.com/how-to-get-3-new-listings-fast-page",
  "attract.card2.desc": "For the Producer and/or Team Leader doing $200,000+ a year, wants more but without giving up their life. This is a 1 on 1 experience that will transform your business and life at scale. Apply for your free business evaluation call and secure your spot today.",
  "attract.card2.buttonText": "Apply Now",
  "attract.card2.url": "https://calendly.com/coachbrianmoses/30-minute-business-assessment-clone",
  "outcomes.heading1": "Your Growth Deserves More Than Advice.",
  "outcomes.heading2": "It Deserves Proven Experience.",
  "outcomes.heading3": "The Real Estate Coach You Hire Matters!",
  "outcomes.statement": "Just like there's no shortage of real estate agents, there's no shortage of self proclaimed coaches... The difference comes down to experience.",
  "outcomes.section1.title": "When Choosing a Coach, Experience Matters",
  "outcomes.section1.p1": "It matters whether they've actually accomplished what you're trying to achieve - or whether they're simply repeating what they've been taught.",
  "outcomes.section1.p2": "Many large coaching organizations rely on active agents to coach on the side. While well intended, their guidance is often limited to personal experience and constrained by their own production demands.",
  "outcomes.section2.title": "Brian Moses Brings a Different Level of Depth",
  "outcomes.section2.p1": "He has sold more than 3,500 homes, twice been ranked #2 worldwide and amongst the top 10 in sales for seven consecutive years.",
  "outcomes.section2.p2": "Beyond production, Brian worked directly for Tony Robbins & Chet Holmes at Business Breakthroughs International as a Sr. Level Executive Business Strategist, gaining elite training in business optimization, scalability and performance maximization.",
  "outcomes.section3.title": "No One-Size-Fits-All Approach",
  "outcomes.section3.p": "When it comes to growing and scaling your business. Brian's customizes your coaching to the agent, their goals and is specific to their market, resulting in a sustainable system, measured results and increased profitability.",
  "outcomes.section4.title": "Mastering Human Performance",
  "outcomes.section4.p": "Beyond production and strategy, lasting growth requires mastering human performance. For more than 30 years Brian has worked in close alignment with Tony Robbins and Robbins Research International, developing deep expertise in human psychology, behavior change and peak performance. This added skill and experience allows him to identify the real constraints holding agents back - often not market conditions or lead flow but unseen limiting beliefs, comfort zones and unconscious patterns that sabotage growth.",
  "outcomes.closing": "Brian's Strategies have been proven repeatedly through the success of the thousands he has impacted over the years.",
  "outcomes.outcome1.title": "Immediately Increase Your Sales",
  "outcomes.outcome1.desc": "Learn strategies to 'reduce your wasteful expenses and increase your sales and income immediately'",
  "outcomes.outcome2.title": "Dominate Your Local Market",
  "outcomes.outcome2.desc": "Discover how to 'attract buyers and sellers, differentiate yourself from your competitors, increase your average sales price, and become the dominant agent in your market!'",
  "outcomes.outcome3.title": "Build a Predictable Business",
  "outcomes.outcome3.desc": "Create a real estate business that offers 'predictability' and allows you to 'take time off,' freeing you from being constantly on call.",
  "outcomes.outcome4.title": "Create the Life You Desire",
  "outcomes.outcome4.desc": "Design 'the business and life you desire', achieving financial freedom that serves your overall happiness.",
  "outcomes.outcome5.title": "Attract Lots of Qualified Leads",
  "outcomes.outcome5.desc": "Implement 'strategies, principals and quality lead generation best practices that will accelerate your income and transform your life!'. Ensure a 'consistent flow, a steady stream of highly motivated leads' right to you.",
  "outcomes.cta1.desc": "For the agent producing 0-15 sales annually, income is under $200,000 and they want a system and process that's predictable, reliable and duplicatable to produce more FAST!",
  "outcomes.cta1.buttonText": "Inner Circle Group Coaching",
  "outcomes.cta1.url": "https://inner-circle.brianmoses.com/how-to-get-3-new-listings-fast-page",
  "outcomes.cta2.desc": "For the Producer and/or Team Leader doing $200,000+ a year, wants more but without giving up their life. This is a 1 on 1 experience that will transform your business and life at scale. Apply for your free business evaluation call and secure your spot today.",
  "outcomes.cta2.buttonText": "Apply Now",
  "outcomes.cta2.url": "https://calendly.com/coachbrianmoses/30-minute-business-assessment-clone",
  "story.headline": "From just $18K a year\ndeep in debt\nto #2 in the World!",
  "story.subheadline": "Brian's Struggle is Your Shortcut",
  "story.p1": "Before Brian Moses became one of the world's top real estate coaches, he was on the verge of quitting. Earning just $18,000 his first year and struggling for five more, he hit the same walls you have. He experienced the hustle, the doubt, and the burnout.",
  "story.p2": "Then, everything changed.",
  "story.p3": "He stopped chasing leads and started building a system. Guided by mentors like Tony Robbins, Bob Proctor and the most successful agents across North America, he transformed his mindset and his business, scaling to $3M+ per year in commissions and selling over 3,500 homes.",
  "story.p4": "",
  "story.quote": "Don't hunt & chase business,\nbecome the one your market can't ignore.",
  "story.intro": "He's offering you the exact playbook he built from the ground up, so you don't have to learn the hard way.",
  "story.principlesHeading": "This philosophy is built on three core principles:",
  "story.principle1.title": "Strategic Action, Not a Numbers Game",
  "story.principle1.desc": "Brian rejects outdated advice like \"just talk to more people.\" He insists there is a better way and will show you how to craft offers so compelling that high-quality buyers and sellers seek you out, allowing you to build a business that works even when you're not. Never worry about where your next deal is coming from, ever again.",
  "story.principle2.title": "Life Beyond the Hustle",
  "story.principle2.desc": "Your business should serve your life, not consume it. Say goodbye to 24/7/365 always on call and tap into a system and process to achieve true freedom, giving you back time for what matters most: your family, your health, and your passions.",
  "story.principle3.title": "A \"Never Say Can't\" Mindset",
  "story.principle3.desc": "Brian's greatest win wasn't the real estate successes he's had. He'd tell you it was the adversities he overcame, the life he provided for his family and the thousands he has helped and impacted over the years. His life story is now being developed into a major motion picture to inspire the world the same way his work has inspired so many.",
  "quote.text": "\"Success isn't just about what you earn. It's about what you get to experience because of what you earn.\"",
  "quote.attribution": "BRIAN MOSES",
  "quote.desc": "If you're ready to stop chasing and start attracting a better business and life, Brian is your guide.",
  "quote.buttonText": "Book a Free Discovery Call",
  "quote.buttonUrl": "https://calendly.com/coachbrianmoses/30-minute-business-assessment-clone",
  "learn.label": "Your Personal Transformation",
  "learn.heading": "Acquire the Mindset and Skills for Success in Real Estate and Life",
  "learn.intro": "Brian Moses' coaching programs are built on a powerful foundation of mindset and skill development - principles that go far beyond real estate and elevate every area of your life. Skills can be learned and by adopting the right approach, you can achieve anything you desire.",
  "learn.buttonText": "Book a Free Discovery Call",
  "learn.buttonUrl": "https://calendly.com/coachbrianmoses/30-minute-business-assessment-clone",
  "learn.item1.title": "Strategic Thinking Over Brute Force",
  "learn.item1.desc": "Transition from sales person to order taker. No one likes a sales person. No one likes to be pitched.\n\nSTOP the old school pitching, closing techniques and learn the skills to stating your value propositions that are unique, compelling, different and irresistible.\n\nYou don't need to close clients, they will choose you.",
  "learn.item2.title": "Embrace Change, Don't Resist It",
  "learn.item2.desc": "Every market shift creates winners and losers.\n\nBrian shows you how to adjust your strategy, messaging, and offers that will stand the test of time.\n\nWhen the market dips, you actually do better because you have a proven process and system that is recession proof.",
  "learn.item3.title": "Relax Your Ego, Add Value",
  "learn.item3.desc": "The fastest way to lose trust is to make it about you.\n\nBrian teaches you how to shift from proving yourself to serving your market—so clients feel understood, supported, and confident choosing you without feeling pressure, pitched or sold.",
  "learn.item4.title": "Learn from Proven Success",
  "learn.item4.desc": "Every strategy Brian teaches has been pressure-tested in competitive markets and all with proven results and success stories.\n\nYou'll learn exactly what works, why it works, and how to apply it immediately.\n\nNo wasting time on tactics that don't move the needle.",
  "workless.headline": "Work less. Earn more.",
  "workless.desc": "You don't need to work harder to live a fullfilled life. You need a better system. If you're ready for more clarity, more income, and more freedom, your journey starts here.",
  "workless.buttonText": "Book a Free Discovery Call",
  "workless.buttonUrl": "https://calendly.com/coachbrianmoses/30-minute-business-assessment-clone",
};

export function getDefault(key: string): string {
  return DEFAULT_CONTENT[key] ?? "";
}
