export const DEFAULT_TESTIMONIALS = [
  { header: "Brian, Great call with our team yesterday! You were right everyone was engaged.", body: "I've been a student of Brian's for over 10 years and he's helped me grow my business and my team exponentially. I'm forever grateful for his guidance.", author: "Jared & Victoria Erfle", title: "Palmdale CA", image: "/images/testimonials/Jared_Victoria_Erfle.png", order: 0 },
  { header: "We generated 100 leads in 24 hours and 8 appointments booked!", body: "This is amazing! All of our team is so excited. We can't wait to see what else we can do with your help!", author: "Andy Richardson", title: "Wilmington, DE", image: "/images/testimonials/Andy_Richardson.png", order: 1 },
  { header: "Thank you from the bottom of my heart!", body: "I've been a student of Brian's for over 10 years and he's helped me grow my business and my team exponentially. I'm forever grateful for his guidance.", author: "Jeremy Mellick", title: "Seattle, WA", image: "/images/testimonials/Jeremy_Mellick.png", order: 2 },
  { header: "Brian Moses is The Master and Original!", body: "One of the people that inspired me to get into the business of coaching and I'm forever grateful for his mentorship.", author: "Jay Kinder", title: "Laughton, OK", image: "/images/testimonials/Jay_Kinder.png", order: 3 },
  { header: "Brian has been an invaluable source of experience and wisdom in our industry!", body: "He's helped me to navigate challenging markets and has always been a guiding light. I'm so grateful for his insights and advice.", author: "Amy Stoehr", title: "CEO Star Power", image: "/images/testimonials/Ame_Stoehr.png", order: 4 },
  { header: "I met Brian in the early 90's and have been impressed with his accomplishments ever since!", body: "He is a true inspiration to the real estate industry and has always been a mentor to me. I'm grateful for his friendship and guidance.", author: "Lillian Montalto", title: "Featured on Lottery Dream Home", image: "/images/testimonials/Lillian_Montalto.png", order: 5 },
  { header: "Brian Moses was a huge inspiration to me when I started in real estate.", body: "I was one of the first to join his coaching program and it helped me grow my business, doubling my production in my first year and then tripling it the second. I'm forever grateful for his guidance.", author: "Anthony Lamacchia", title: "Offices in MA, NH, CT, ME, RI & FL - Over 2 Billion in Annual Sales Volume", image: "/images/testimonials/Anthony_Lamachhia.png", order: 6 },
  { header: "One of the best real estate coaches in the entire Industry!", body: "Brian has worked with our company for a long time, I've personally worked with Brian 1 on 1, I've seen him speak multiple times over the last 15 years, he's worked with our team, worked with a lot of our clients, he's terrific.", author: "Shant Banosian", title: "President RATE Mortgage", image: "/images/testimonials/Shant_Banosian.png", order: 7 },
  { header: "Brian is an absolute hero of mine!", body: "He was instrumental in helping me go from 40 deals a year to over 400! He is super smart, world class coach & trainer and I am a HUGE fan!", author: "Brent Gove", title: "Sacramento, CA", image: "/new_testimonials_v2/Brent_Gove.jpg", order: 8 },
  { header: "I brought Brian in to close out my annual 3 day RATE Mastermind,", body: "event packed with industry heavyweights because I needed someone exceptional. Over the last 20 years I've watched him consistently produce results for top agents across the country. If you're looking for impact and results, Brian won't disappoint.", author: "Matt Wagner", title: "CEO, Radio & Television Experts / RATE", image: "/new_testimonials_v2/Matt_Wagner.jpg", order: 9 },
  { header: "Brian, I wanted to share, our team closed $700K in GCI last month!", body: "Thanks for all your help!", author: "Nick McLean", title: "Nick McLean Nation", image: "/new_testimonials_v2/Nick_McLean.jpg", order: 10 },
];
